#
# Dockerfile to launch the project at once.
# See https://docs.docker.com/compose/compose-file/ for reference.
#

services:
  fsociety:
    build:
      context: .
      dockerfile: fsociety/Dockerfile
    expose:
      - 22
      - 4200
    environment:
      SIAB_USER: elliot
      SIAB_PASSWORD: fsociety1986
      SIAB_ADDUSER: false
      SIAB_SSL: false
      SIAB_USERCSS: 'Normal:-/etc/shellinabox/options-enabled/00+Black-on-White.css,Reverse:+/etc/shellinabox/options-enabled/00_White-On-Black.css;Colors:+/etc/shellinabox/options-enabled/01+Color-Terminal.css,Monochrome:-/etc/shellinabox/options-enabled/01_Monochrome.css'
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    external: true

