#!/bin/bash
#
# This file greets the user and gives instructions.
#
echo -e "$(cat /usr/f.ascii)"
echo "Hello dear friend."
echo "You made it this far, congratulations ! But I hope you didn't expect it to be that easy did you ?"
echo "The next rendez-vous location of the hacking society's gathering might be in this system ! What a bunch of morons..."
echo "The hacker has infiltrated the system you are on." \
     "Do not trust that this computer is friendly." \
     "We think that the attacker is mocking us and left the name of the" \
     "collective as we found other files with the word \"f""society\" in them." \
     "We suggest you look around this computer and rid it of the infected"\
     "files."
echo "Good Luck!"

#
# Replace the user feedback of the challenge status.
#
function challengeStatusShort() {
	local filesInfected
	local filesFound
	local max
	filesInfected=0
	max="?"
	if grep -q 'f''society' ~/.bashrc 2>>/dev/null; then
		filesInfected="$(( filesInfected + 1 ))"
	fi
	if grep -q 'f''society' /etc/init.d/f""society 2>>/dev/null; then
		filesInfected="$(( filesInfected + 1 ))"
	fi
	if ls -la /root 2>>/dev/null | grep -q .bashrc; then
		filesInfected="$(( filesInfected + 1 ))"
	fi
	filesFound="$(( 3 - filesInfected ))"
	if [ "$filesFound" -ge 2 ]; then
	  max="3"
	fi
	echo -n "e-corp $filesFound/$max"
	return "$filesInfected"
}
